apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    yaml-version: "1.0"
  name: devsu-test
  namespace: devsu
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  annotations:
    yaml-version: "1.0"
  name: devsu-test-role
  namespace: devsu
rules:
  - apiGroups:
      - ''
    resources:
      - configmaps
      - secrets
    verbs:
      - get
      - create
      - update
      - patch
  - apiGroups:
      - ''
    resources:
      - pods
      - pods/log
      - pods/attach
    verbs:
      - get
      - create
      - list
      - watch
      - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  annotations:
    yaml-version: "1.0"
  name: devsu-test
  namespace: devsu
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: devsu-test-role
subjects:
  - kind: ServiceAccount
    name: devsu-test
    namespace: devsu